Diccionario con la letra 'a':
Traceback (most recent call last):
  File "C:\Users\Lenovo\Desktop\pythoncore2025\class_5\Section_3Error Detection\Lab3\Section_1 Programming Practice\task_2.py", line 52, in <module>
    a_dict[key] = value1
                  ^^^^^^
NameError: name 'value1' is not defined. Did you mean: 'value'?